-- CONSULTA DE ITENS NOVOS CADASTRADOS
-- ===================================
--Código / Descrição / Subgrupo / Marca / Referência / EAN / Saldo

USE OXICLOUD23

SELECT DISTINCT B1_GRUPO GRUPO, BM_DESC 'DESCRICAO GRUPO', B1_MARCA MARCA, ZZ1_DESC 'DESCRICAO MARCA', 
				B1_COD CODIGO, B1_DESC DESCRICAO, B1_SUBGRUP SUBGRUPO, RTRIM(B1_FABRIC) 'REF. FABR',B1_CODBOXI EAN,
(SELECT SUM(B2_QATU) FROM SB2010 B2 WHERE B2_COD = B1_COD AND B2.D_E_L_E_T_ <> '*') SALDO,

SUBSTRING(B1_DTCAD,7,2)+'/'+SUBSTRING(B1_DTCAD,5,2)+'/'+SUBSTRING(B1_DTCAD,1,4) 'DATA CADASTRO',
SUBSTRING(B1_UCOM,7,2)+'/'+SUBSTRING(B1_UCOM,5,2)+'/'+SUBSTRING(B1_UCOM,1,4) 'DATA ULTIMA COMPRA',

CASE WHEN B1_IMAGEM = 'T' THEN 'SIM' ELSE 'NAO' END AS IMAGEM,
CASE WHEN B5_DESCSER IS NULL THEN 'NAO' ELSE 'SIM' END AS 'ESPECIFICACAO TECNICA',
CASE WHEN B1_SUBGRUP = '100' THEN 'SIM' ELSE 'NAO' END AS 'VENDA CASADA',
CASE WHEN B1_DESC_P <> '' THEN 'SIM' ELSE 'NAO' END AS ESP_TEC

FROM SB1010 B1
LEFT OUTER JOIN SB5010 SB5 ON B5_COD = B1_COD
INNER JOIN SBM010 ON B1_GRUPO = BM_GRUPO
INNER JOIN ZZ1010 ON B1_MARCA = ZZ1_MARCA
WHERE B1.D_E_L_E_T_ <> '*'
AND SBM010.D_E_L_E_T_ <> '*'
AND ZZ1010.D_E_L_E_T_ <> '*'
AND B1_SUBGRUP <> '100'-- DIFERENTE DE 100 SIGNIFICA QUE NÃO É VENDA CASADA

-- Colocar a data do periodo a que se refere a consulta
AND B1_DTCAD BETWEEN '20200925' AND '20201207'
 

ORDER BY B1_COD


--CONSULTA PRODUTOS @BY ADRIANO

SELECT B1_COD, B1_DESC, B1_FABRIC 'REF. FABR',B1_CODBOXI EAN, B1_GRUPO
			
			FROM SB1010 B1
						LEFT OUTER JOIN SB5010 SB5 ON B5_COD = B1_COD
						INNER JOIN SBM010 ON B1_GRUPO = BM_GRUPO
						INNER JOIN ZZ1010 ON B1_MARCA = ZZ1_MARCA
						INNER JOIN ZZ8010 ON B1_COD = ZZ8_PROD
			WHERE B1.D_E_L_E_T_ <> '*'
					AND SBM010.D_E_L_E_T_ <> '*'
					AND ZZ1010.D_E_L_E_T_ <> '*' 
				--	AND ZZ8_FORAL <> '1'	--FORA DE LINHA 1
					AND ZZ8_ECOM <> '1'  -- VENDA CASA 1 
					AND	B1_DTCAD BETWEEN '20190101' AND '20201117'
				  --AND B1_GRUPO = '' 
					AND B1_MARCA = '084' 
ORDER BY 1



--PRODUTOS CADASTRO DE IMPOSTOS SACOMAN COM VENDA CASADA E SEM.


SELECT DISTINCT  B1_COD, B1_DESC, B1_ICMSC, B1_ICMSV, B1_TE, B1_TS, B1_POSIPI, B1_PICM, B1_IPI, B1_PICMENT, B1_ORIGEM, B1_CLASFIS, B1_GRTRIB, ZZ8_ICMSC, ZZ8_ICMSV --B2_QATU
FROM SB1010, ZZ8010, SB2010
WHERE B1_COD = ZZ8_PROD AND B1_COD = B2_COD AND SB1010.D_E_L_E_T_ <> '*' AND SB2010.D_E_L_E_T_ <> '*' AND ZZ8010.D_E_L_E_T_ <> '*'
AND B1_MSBLQL = '2' 
AND B1_SUBGRUP = '100' AND B1_VENCAS = 'S' 
AND B2_QATU <> '0'

