
-- VERIFICA QUAIS PRODUTOS ESTÃO COM IMAGEM (T=TRUE/VERDADEIRO)
SELECT * FROM SB1010 WHERE B1_IMAGEM = 'T';

-- VERIFICA QUAIS PRODUTOS NÃO ESTÃO COM IMAGEM (F=FALSE/FALSO)
SELECT * FROM SB1010 WHERE B1_IMAGEM = 'F';

-- FORÇA A IMAGEM EM TODOS OS PRODUTOS (USANDO O 'T' NO CAMPO B1_IMAGEM)
UPDATE SB1010 SET B1_IMAGEM = 'T';
