
--Criação de View Banco de dados OXICLOUD

ALTER VIEW  REGION  AS 
SELECT * 
FROM OXICLOUD23.dbo.ZZ9010 WHERE  D_E_L_E_T_ = ''



-- VIEW PAIS 
ALTER VIEW  PAIS  AS 
SELECT DISTINCT X5_TABELA, X5_CHAVE, X5_DESCRI, X5_DESCSPA, X5_DESCENG
FROM OXICLOUD23.dbo.SX5010 WHERE X5_TABELA = 'HC'
AND D_E_L_E_T_ = ''

SELECT * FROM PAIS

-- vIEW cnae

CREATE VIEW  CNAE  AS 
SELECT * 
FROM OXICLOUD23.dbo.CC3010 WHERE  D_E_L_E_T_ = ''



-- VIEW DE MOTIVOS DE CANCELAMENTOS DE VENDAS PERDIDAS
CREATE VIEW  MOTIVO_CANCELAMENTO  AS 
SELECT * 
FROM OXICLOUD23.dbo.ZZN010 WHERE  D_E_L_E_T_ = ''


--VIEW CIDADES
CREATE VIEW  CIDADES  AS 
SELECT * 
FROM OXICLOUD23.dbo.CC2010 WHERE  D_E_L_E_T_ = ''


-- VIEW OCORRENCIA
CREATE VIEW  OCORRENCIA  AS 
SELECT U9_CODIGO   AS COD_OCORRENCIA
     , U9_DESC     AS DES_OCORRENCIA
  FROM OXICLOUD23.dbo.SU9010
 WHERE U9_VALIDO ='1' 
   AND U9_TIPOATE IN ('2','4') 
   AND D_E_L_E_T_ = '';

