-- EXECUTAR PARA O MÊS VIGENTE
-- ENTRAR NO PROTHEUS, MODULO FATURAMENTO E PESQUISAR OX_CURVA, AJUSTAR DATA COM INICIO DO MÊS ANTERIOR EX.: 01/05/22 - APÓS FINALIZAR A CARGA A TELA FECHA.

--AJUSTAR DATA NOS COMANDOS ABAIXO IGUAL AO MÊS DE EXECUÇÃO
--PROXIMA MÊS 05

-- Quantidade de itens ativos - COPIAR A QUANTIDADE DE ITÉNS ATIVOS E COLAR 
USE OXICLOUD27
SELECT COUNT(1) FROM TAB_CURVA_ABCD WHERE DT_REF LIKE '202204%'
GO
/*
-- Planilha Rogério inicio de Mês (Aba Dados Produtos)
*/
SELECT A.B1_COD,
       A.B1_DESC,
	   A.QTD_TOT "QTD VENDIDA",
	   REPLACE(ROUND(A.QTD_TOT*A.PRC_VENDA,2),'.', ',') "TOTAL VENDAS",
	   REPLACE(ROUND(A.QTD_TOT*A.CUSTO_FINAN_CALC,2), '.', ',') "TOTAL CUSTO",
	   REPLACE(ROUND(((A.QTD_TOT*A.PRC_VENDA)-(A.QTD_TOT*A.CUSTO_FINAN_CALC)), 2), '.', ',') MARGEM,
	   A.CURVA_MARGEM,
	   A.CURVA_VOLUME 
FROM TAB_CURVA_ABCD A
WHERE A.QTD_TOT > 0 AND A.CUSTO_FINAN_CALC <> A.PRC_VENDA AND A.DT_REF LIKE '202204%'
GROUP BY A.B1_COD, A.B1_DESC,A.PRC_VENDA,A.CUSTO_FINAN_CALC, A.QTD_TOT, A.CURVA_MARGEM, A.CURVA_VOLUME
ORDER BY 7, 8, 6 DESC

-- Curva Margem
SELECT A.B1_COD,
	   REPLACE(ROUND(A.QTD_TOT/
	   (SELECT SUM(B.QTD_TOT) FROM TAB_CURVA_ABCD B WHERE B.QTD_TOT > 0 AND B.CUSTO_FINAN_CALC <> B.PRC_VENDA), 4), '.', ',') PARTIC,
	   A.CURVA_MARGEM
FROM TAB_CURVA_ABCD A
WHERE A.QTD_TOT > 0 AND A.CUSTO_FINAN_CALC <> A.PRC_VENDA AND A.DT_REF LIKE '202204%'
GROUP BY A.B1_COD, A.QTD_TOT, A.CURVA_MARGEM
ORDER BY 3, 2 DESC

-- Curva Volume
SELECT A.B1_COD,
	   REPLACE(ROUND(A.QTD_TOT/
	   (SELECT SUM(B.QTD_TOT) FROM TAB_CURVA_ABCD B WHERE B.QTD_TOT > 0 AND B.CUSTO_FINAN_CALC <> B.PRC_VENDA), 4), '.', ',') PARTIC,
	   A.CURVA_VOLUME
FROM TAB_CURVA_ABCD A
WHERE A.QTD_TOT > 0 AND A.CUSTO_FINAN_CALC <> A.PRC_VENDA AND A.DT_REF LIKE '202204%'
GROUP BY A.B1_COD, A.QTD_TOT, A.CURVA_VOLUME
ORDER BY 3, 2 DESC


-- APÓS FINALIZAR OS PROCESSOS ACIMA, EXECUTAR UPDATE ABAIXO --- ESTE COMANDO MUDA A COR DAS BOLAS DA CONSULTA DE PREÇO 
--UPDATE ZZ8010 SET ZZ8_LIQUI = '0', ZZ8_LIQUI2 = '0'

 