select DISTINCT A1_COD, A1_NOME, A1_PESSOA, A1_MUNC, A1_ESTC, A1_CONTATO ,A1_EMAILC, A1_EMAIL AS EMAILS, A1_ULTCOM 
		
		from SA1010 

		WHERE  A1_EMAILC LIKE '%@%' OR A1_EMAIL LIKE '%@%' 

 GROUP BY A1_COD, A1_NOME, A1_PESSOA, A1_MUNC, A1_ESTC, A1_CONTATO ,A1_EMAILC, A1_EMAIL, A1_ULTCOM 
ORDER BY 8

--A1_ULTCOM >='2018%'    AND 

--SELECT * from SA1010 

--SELECT * FROM SA1010 

SELECT DISTINCT U5_CONTAT, U5_EMAIL, U5_OXINCLI FROM SU5010 WHERE  U5_EMAIL LIKE '%@%'