/*  GRUPO NOTA E CODLAN  */
WITH TMP AS 
(SELECT F1_FORNECE,F1_LOJA,F1_DOC,D1_CF,F1_ESPECIE,F1_DTDIGIT,F1_EST,F1_FILIAL,F1_TIPO,CDA_CODLAN,F1_SERIE,F1_EMISSAO
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_TOTAL   ELSE 0 END) TOTAL
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_BASEICM ELSE 0 END) BASEICM
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_VALICM ELSE 0 END) VALICM
,ISNULL(
CASE WHEN CDA_CODLAN = 'SP90090104' THEN
(SELECT SUM(F3_ISENICM) FROM SF3010 F3 (NOLOCK) WHERE F3_CLIEFOR = F1_FORNECE AND F3_LOJA = F1_LOJA AND F3_NFISCAL = F1_DOC AND F3_SERIE = F1_SERIE AND F3.D_E_L_E_T_='')ELSE 0 END,0)ISENICM
,ISNULL(
CASE WHEN CDA_CODLAN = 'SP90090104' THEN
(SELECT SUM(F3_OUTRICM) FROM SF3010 F3 (NOLOCK) WHERE F3_CLIEFOR = F1_FORNECE AND F3_LOJA = F1_LOJA AND F3_NFISCAL = F1_DOC AND F3_SERIE = F1_SERIE AND F3.D_E_L_E_T_='')ELSE 0 END,0)OUTRICM
,ISNULL(CDA_CODLAN,0)CODLAN 
,ISNULL(SUM(CDA_VALOR),0) VALOR
,ISNULL(SUM(CDA_BASE),0) BASE
FROM SF1010 F1 (NOLOCK)
INNER JOIN SD1010 D1 (NOLOCK) ON D1_FORNECE = F1_FORNECE AND D1_LOJA = F1_LOJA AND D1_DOC = F1_DOC AND D1_SERIE = F1_SERIE AND D1.D_E_L_E_T_=''
LEFT OUTER JOIN CDA010 DA (NOLOCK) ON CDA_CLIFOR = F1_FORNECE AND CDA_LOJA = F1_LOJA AND CDA_NUMERO = F1_DOC AND CDA_SERIE = F1_SERIE AND CDA_NUMITE = D1_ITEM AND DA.D_E_L_E_T_=''
WHERE F1_DTDIGIT LIKE '20220214%' AND F1.D_E_L_E_T_ = '' AND F1_FILIAL = '01' AND F1_ESPECIE NOT IN ('CTE','NFS')
--AND D1_DOC = '000658876'
GROUP BY F1_FORNECE,F1_LOJA,F1_DOC,D1_CF,F1_SERIE,CDA_CODLAN,F1_ESPECIE,F1_DTDIGIT,F1_EST,F1_FILIAL,F1_TIPO,F1_EMISSAO)

SELECT F1_FILIAL
,CONVERT(varchar, CAST(F1_DTDIGIT AS datetime), 103) F1_DTDIGIT
,F1_ESPECIE
,F1_DOC
,CONVERT(varchar, CAST(F1_EMISSAO AS datetime), 103) F1_EMISSAO
,CASE WHEN F1_TIPO IN ('B','D') THEN A1_CGC ELSE A2_CGC END CNPJ
,CASE WHEN F1_TIPO IN ('B','D') THEN A1_NOME ELSE A2_NOME END RAZAO
,F1_EST
,ROUND(SUM(TOTAL),2)TOTAL
,ROUND(SUM(BASEICM),2)BASEICM
,ROUND(SUM(VALICM),2)VALICM
,ISNULL(CDA_CODLAN,'') CODLAN
,ROUND(ISNULL(SUM(VALOR),0),2) VALOR
,ROUND(ISNULL(SUM(BASE),0),2)BASE
,ROUND(SUM(ISENICM),2)ISENICM
,ROUND(SUM(OUTRICM),2)OUTRICM
FROM TMP
LEFT OUTER JOIN SA2010 A2 (NOLOCK) ON F1_FORNECE = A2_COD AND F1_LOJA = A2_LOJA AND A2.D_E_L_E_T_=''
LEFT OUTER JOIN SA1010 A1 (NOLOCK) ON F1_FORNECE = A1_COD AND F1_LOJA = A1_LOJA AND A1.D_E_L_E_T_=''
GROUP BY F1_FORNECE,F1_LOJA,F1_DOC,D1_CF,F1_SERIE,CDA_CODLAN,F1_ESPECIE,F1_DTDIGIT,F1_EST,F1_FILIAL,F1_EMISSAO,A1_CGC,A2_CGC,F1_TIPO,A2_NOME,A1_NOME
ORDER BY F1_DTDIGIT,4
-----



/* GRUPO CFOP */

WITH TMP
AS (SELECT F1_FORNECE,F1_LOJA,F1_DOC,D1_CF,D1_ITEM
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_TOTAL   ELSE 0 END) TOTAL
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_BASEICM ELSE 0 END) BASEICM
,SUM(CASE WHEN CDA_CODLAN = 'SP90090104' THEN D1_VALICM ELSE 0 END) VALICM
,ISNULL(
CASE WHEN CDA_CODLAN = 'SP90090104' THEN
(SELECT SUM(F3_ISENICM) FROM SF3010 F3 (NOLOCK) 
WHERE F3_CLIEFOR = F1_FORNECE AND F3_LOJA = F1_LOJA AND F3_NFISCAL = F1_DOC AND F3_SERIE = F1_SERIE AND F3.D_E_L_E_T_='' AND F3_ESPECIE NOT IN ('CTE','NFS'))ELSE 0 END,0)ISENICM
,ISNULL(
CASE WHEN CDA_CODLAN = 'SP90090104' THEN
(SELECT SUM(F3_OUTRICM) FROM SF3010 F3 (NOLOCK) 
WHERE F3_CLIEFOR = F1_FORNECE AND F3_LOJA = F1_LOJA AND F3_NFISCAL = F1_DOC AND F3_SERIE = F1_SERIE AND F3.D_E_L_E_T_=''AND F3_ESPECIE NOT IN ('CTE','NFS'))ELSE 0 END,0)OUTRICM
,ISNULL(CDA_CODLAN,0)CODLAN ,ISNULL(SUM(CDA_VALOR),0) VALOR,ISNULL(SUM(CDA_BASE),0) BASE
FROM SF1010 F1 (NOLOCK)
INNER JOIN SD1010 D1 (NOLOCK) ON D1_FORNECE = F1_FORNECE AND D1_LOJA = F1_LOJA AND D1_DOC = F1_DOC AND D1_SERIE = F1_SERIE AND D1.D_E_L_E_T_=''
LEFT OUTER JOIN CDA010 DA (NOLOCK) ON CDA_CLIFOR = F1_FORNECE AND CDA_LOJA = F1_LOJA AND CDA_NUMERO = F1_DOC AND CDA_SERIE = F1_SERIE AND CDA_NUMITE = D1_ITEM AND DA.D_E_L_E_T_=''
WHERE F1_DTDIGIT LIKE '20220214%' AND F1.D_E_L_E_T_ = '' AND F1_FILIAL = '01' AND F1_ESPECIE NOT IN ('CTE','NFS')
--AND D1_DOC = '000970855'
GROUP BY F1_FORNECE,F1_LOJA,F1_DOC,D1_CF,F1_SERIE,D1_ITEM,CDA_CODLAN)

SELECT D1_CF,CODLAN
,ROUND(SUM(TOTAL),2)TOTAL
,ROUND(SUM(BASEICM),2)BASEICM
,ROUND(SUM(VALICM),2)VALICM
,ROUND(SUM(ISENICM),2)ISENICM
,ROUND(SUM(OUTRICM),2)OUTRICM
,ROUND(ISNULL(SUM(VALOR),0),2) VALOR
,ROUND(ISNULL(SUM(BASE),0),2)BASE
FROM TMP
GROUP BY D1_CF,CODLAN
ORDER BY D1_CF,CODLAN

/* GRUPO CODLAN*/
SELECT CDA_CODLAN, SUM(CDA_VALOR) VALOR,SUM(CDA_BASE) BASE
FROM CDA010 DA
INNER JOIN SF1010 F1 (NOLOCK) ON CDA_NUMERO = F1_DOC AND CDA_ESPECI = F1_ESPECIE AND CDA_SERIE = F1_SERIE AND CDA_FILIAL = F1_FILIAL AND F1.D_E_L_E_T_ =''
AND F1_DTDIGIT LIKE '20220214%' AND F1_FILIAL = CDA_FILIAL AND F1_ESPECIE NOT IN ('CTE','NFS')
WHERE DA.D_E_L_E_T_='' AND CDA_FILIAL = '01'
GROUP BY CDA_CODLAN


