UPDATE SB2010 SET B2_QEMP =
--SELECT 
ISNULL((SELECT SUM (ZZB_QUANT-ZZB_DEVOL-ZZB_LIBER) 
FROM ZZB010 ZB
--INNER JOIN ZZB010 ZB ON 
INNER JOIN ZZA010 ZA ON ZZB_FILIAL = ZZA_FILIAL AND ZZB_VALE = ZZA_VALE AND (ZZA_STATUS <> 'B' AND ZZA_STATUS <> 'C') AND ZA.D_E_L_E_T_ ='' 
WHERE ZZB_PRODUT = B2_COD AND ZZB_LOCAL = B2_LOCAL AND ZB.D_E_L_E_T_ =''
AND ZZB_QUANT > (ZZB_DEVOL+ZZB_LIBER) AND ZB.D_E_L_E_T_ ='' AND ZZB_FILIAL = B2_FILIAL 
),0)
FROM SB2010 B2
WHERE -- B2_COD = '031870003' AND 
B2_FILIAL = '02'