select D1_DOC , COUNT ( * ) QTDITEM , D1_DTDIGIT , A2_NREDUZ , F1_DTVENC DTVE , D1_PEDIDO PEDIDO , ( ZR1_DATA + ZR1_HORA ) RECN , 
( select MAX ( ZRL_DATA + ZRL_HORA ) 
from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMPED = RTRIM ( D1_PEDIDO ) and D_E_L_E_T_ < > '*' 
and ZRL_ACAO like '%LIBERACAO DO PEDIDO%' ) LIPE , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMPED = RTRIM 
( D1_PEDIDO ) and ZRL_NUMDOC = D1_DOC and D_E_L_E_T_ < > '*' and ZRL_ACAO like '%COMPL. PRE-NOTA INICIO%' ) CPIN , 
( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMPED = RTRIM ( D1_PEDIDO ) 
and ZRL_NUMDOC = D1_DOC and D_E_L_E_T_ < > '*' and ZRL_ACAO like '%COMPL. PRE-NOTA FIM%' ) CPFI , 
( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) 
and D_E_L_E_T_ < > '*' and ZRL_ACAO like 'ENTRADA PRE NOTA' ) ENPN , 
( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' 
and ZRL_ACAO like '%FISÍCA INICIO' ) COFI , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) 
and D_E_L_E_T_ < > '*' and ZRL_ACAO like '%FISÍCA FIM' ) COFF , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' 
and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' and ZRL_ACAO like 'DIGITAÇÃO ESPELHO CEGO' ) DIEC , 
( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' 
and ZRL_ACAO like 'CLASSIFICAÇÃO DA NOTA' ) CLNO , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' 
and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' and ZRL_ACAO like 'IMPRESSÃO DA CRITICA' ) IMCR , 
( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' 
and ZRL_ACAO like 'INICIO GUARDA' ) INGU , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' and ZRL_NUMDOC = RTRIM ( D1_DOC ) 
and D_E_L_E_T_ < > '*' and ZRL_ACAO like 'FIM GUARDA' ) FIGU , ( select MAX ( ZRL_DATA + ZRL_HORA ) from ZRL010 where ZRL_TIPO = 'C' 
and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > '*' and ZRL_ACAO like '%LIBERAÇÃO POR SENHA%' ) LISE from SF1010 F1 
inner join SD1010 D1 on D1_DOC = F1_DOC and D1_SERIE = F1_SERIE and D1_FORNECE = F1_FORNECE and D1_PEDIDO < > @0 and D1 . D_E_L_E_T_ < > @1 
left outer join SF4010 F4 on F4_CODIGO = D1_TES and F4_ESTOQUE = @2 and F4 . D_E_L_E_T_ < > @3 and ( F4_VALPED is null or F4_VALPED = @4 ) 
inner join SA2010 A2 on A2_COD = D1_FORNECE and A2_LOJA = D1_LOJA and A2 . D_E_L_E_T_ < > @5 
inner join ZR1010 R1 on ZR1_FILIAL = F1_FILIAL and ZR1_CHVNFE = F1_CHVNFE and R1 . D_E_L_E_T_ = @6 
and ( ZR1_DATA between @7 and @8 or ZR1_RECP = @9 ) where F1_DTDIGIT > = @10 and F1 . D_E_L_E_T_ < > @11 and not exists 
( select 1 from ZRL010 where ZRL_TIPO = @12 and ZRL_NUMDOC = RTRIM ( D1_DOC ) and D_E_L_E_T_ < > @13 and ZRL_ACAO like 'FIM GUARDA' ) 
group by D1_DOC , D1_PEDIDO , D1_DTDIGIT , A2_NREDUZ , F1_DTVENC , ZR1_DATA , ZR1_HORA order by RECN


SELECT L4_FILIAL,L4_NUM,L4_DATA,L4_VALOR,L4_FORMA,L4_ADMINIS,L4_NUMCART,L4_AGENCIA,L4_CONTA,L4_RG,L4_TELEFON,L4_OBS,L4_TERCEIR,
			L4_SITUA,L4_DATATEF,L4_HORATEF,L4_DOCTEF,L4_AUTORIZ,L4_DATCANC,L4_HORCANC,L4_DOCCANC,L4_INSTITU,L4_NSUTEF,L4_TIPCART,L4_MOEDA,
			L4_MESACTA,L4_ANOACTA,L4_TIPOCHQ,L4_CGC,L4_NOMECLI,L4_SERCHQ,L4_COMP,L4_ORIGEM,L4_FORMPG,L4_VENDTEF,L4_TROCO,
			--TBL.D_E_L_E_T_,
			L4_FORMAID,
			L4_PARCTEF,L4_ITEM,L4_ESTORN,L4_OPERAES,L4_SERPDV,L4_PAFMD5,L4_DOC,L4_CONTDOC,L4_CONTONF,L4_DESPRC,L4_BANPRC,L4_ACRSFIN,L4_PROCFID,
			L4_NUMCFID,L4_CONHTL,L4_CODVP,L4_DESCMN,L4_BANDEIR,L4_REDEAUT,L4_IDPGVFP,L4_IDRSPFI,L4_YPREFIX,L4_YNUM,L4_YPARCEL,L4_YTIPO,L4_IDCNAB 
			FROM dbo.SL4010 TBL WHERE TBL.R_E_C_N_O_ = ''

SELECT LG_IPSITEF,LG_SERIE,LG_PDV,* FROM SLG010 WHERE D_E_L_E_T_ <> '*'
--UPDATE SLG010 SET LG_IPSITEF = '192.168.0.26' WHERE LG_IPSITEF = '192.168.0.5' AND D_E_L_E_T_ <> '*'