
--fornecedores e clientes que não movimentaram no ultimo ano, alterar o Status dos mesmos para "Pendente de atualização

--SF1	CABECALHO DAS NF’S DE ENTRADA -- FORNECEDORES
--SF2	CABECALHO DAS NF’S DE SAIDA -- CLIENTES

--CLIENTES

select A1_NOME, A1_ULTCOM, COUNT(R_E_C_N_O_) FROM SA1010 
WHERE D_E_L_E_T_ = '' AND A1_ULTCOM <>  '' AND A1_ULTCOM < '20191201' GROUP BY A1_NOME, A1_ULTCOM, R_E_C_N_O_  ORDER BY 2

select A1_NOME, A1_ULTCOM, R_E_C_N_O_ FROM SA1010 
--UPDATE SA1010 SET A1_STATUS = '3'
WHERE A1_MSBLQL = 2 AND D_E_L_E_T_ = '' AND A1_STATUS = '4' AND A1_ULTCOM <> '' AND A1_ULTCOM <= '20191130'  
ORDER BY 3


--FORNECEDORES
SELECT A2_STATUS,A2_ULTCOM,A2_PRICOM, A2_MSBLQL,* FROM SA2010  WHERE A2_MSBLQL = 2 AND D_E_L_E_T_ = '' and A2_ULTCOM <= '20181130'



