--CLIENTES (FILTRO: A1_DTCADAS)
SELECT COUNT(*) FROM SA1VIEW

ALTER VIEW SA1VIEW AS
select
A1_COD,A1_LOJA,A1_NOME,A1_PESSOA,A1_NREDUZ,A1_TIPO,A1_NATUREZ,A1_DDD,
A1_TEL,A1_CGC,A1_INSCR,A1_PFISICA,A1_INSCRM,
--ISNULL(ISNULL((select TOP 1 F2_VEND1 from OXICLOUD23.dbo.SF2010 F2 where F2_CLIENTE = A1_COD and F2_LOJA = A1_LOJA AND F2_EMISSAO = A1_ULTCOM),
--(select top 1 UA_VEND from OXICLOUD23.dbo.SUA010 UA1 where UA_CLIENTE = A1_COD and UA_LOJA = A1_LOJA AND UA_NUM = (select MAX(UA_NUM) from OXICLOUD23.dbo.SUA010 where UA_CLIENTE = A1_COD and UA_LOJA = A1_LOJA and UA_EMISSAO >= '20140101'))),A1_VEND) AS A1_VEND,
--ISNULL((select TOP 1 F2_VEND1 from OXICLOUD23.dbo.SF2010 F2 with (nolock) where F2_CLIENTE = A1_COD and F2_LOJA = A1_LOJA AND F2_EMISSAO = A1_ULTCOM AND F2_EMISSAO BETWEEN '20190101' AND '20191231' ORDER BY F2_EMISSAO DESC), '') AS A1_VEND,
A1_VEND,
A1_RISCO,A1_LC,A1_CLASSE,A1_ULTCOM,
A1_NROCOM,A1_DTNASC,A1_GRPTRIB,A1_EMAIL,A1_HPAGE,A1_MSBLQL,A1_FORMA,A1_FILATR,A1_STATUS,
A1_DTCAD,A1_RESPONS,A1_TELF,A1_REGION,A1_EMAILC,
A1_CNAE AS A1_CNAEP,
A1_CNAE1,A1_CNAE2,A1_CNAE3,A1_CNAE4,A1_CNAE5,A1_CNAE6,A1_CNAE7,A1_CNAE8,A1_DTCADAS,
A1_CEP,A1_END,A1_NUMERO,A1_COMPLEM,A1_BAIRRO,A1_COD_MUN,A1_MUN,A1_EST,
A1_CEPC,A1_ENDCOB,A1_NUMC,A1_BAIRROC,A1_MUNC,A1_ESTC,
A1_CODPAIS,
A1_CODMUN,A1_CODMUNE
FROM OXICLOUD23.dbo.SA1010 with (nolock)
--where A1_COD = '006677'
where A1_COD <> ''
--where D_E_L_E_T_ = ''


--select COUNT(1) from SA1VIEW where A1_VEND = ''
-- 44.909 > 11.177

--CONTATOS X CLIENTES
ALTER VIEW AC8VIEW AS
select AC8_CODCON, A1_COD, A1_LOJA, AC8_DTCADA, A1_DTCAD
from OXICLOUD23.dbo.SA1010 SA1 with (nolock)
left join OXICLOUD23.dbo.AC8010 AC8 with (nolock)
on AC8_CODENT = A1_COD+A1_LOJA -- AC8_CODENT = CODIGO + LOJA DO CLIENTE OU FORNECEDOR
AND AC8_ENTIDA = 'SA1' -- SA1 - CLIENTES OU SA2 - FORNECEDOR
AND AC8.D_E_L_E_T_ = ''
where SA1.D_E_L_E_T_ = '' and A1_COD <> ''

--CONTATOS (FILTRO: U5_DTCADAS)

SELECT * FROM SU5010
ALTER VIEW SU5VIEW AS
select U5_CODCONT,
U5_CONTAT, -- NOME
U5_SOBRENO, -- SOBRENOME
ISNULL((select TOP 1 AGB_DDD from OXICLOUD23.dbo.AGB010 DDDFONE where DDDFONE.AGB_ENTIDA = 'SU5' and DDDFONE.AGB_CODENT = U5_CODCONT and DDDFONE.AGB_TIPO = '2' and DDDFONE.AGB_PADRAO = '1' and DDDFONE.D_E_L_E_T_ = ''), U5_DDD) AS U5_DDD_FONE, -- DDD FONE
ISNULL((select TOP 1 AGB_TELEFO from OXICLOUD23.dbo.AGB010 FONE where FONE.AGB_ENTIDA = 'SU5' and FONE.AGB_CODENT = U5_CODCONT and FONE.AGB_TIPO = '2' and FONE.AGB_PADRAO = '1' and FONE.D_E_L_E_T_ = ''), U5_FONE) AS U5_FONE, -- FONE
(select TOP 1 AGB_DDD from OXICLOUD23.dbo.AGB010 DDDCEL where DDDCEL.AGB_ENTIDA = 'SU5' and DDDCEL.AGB_CODENT = U5_CODCONT and DDDCEL.AGB_TIPO = '5' and DDDCEL.AGB_PADRAO = '1' and DDDCEL.D_E_L_E_T_ = '') AS U5_DDD_CEL, -- DDD CELULAR
(select TOP 1 AGB_TELEFO from OXICLOUD23.dbo.AGB010 CEL where CEL.AGB_ENTIDA = 'SU5' and CEL.AGB_CODENT = U5_CODCONT and CEL.AGB_TIPO = '5' and CEL.AGB_PADRAO = '1' and CEL.D_E_L_E_T_ = '') AS U5_CELULAR, -- CELULAR
U5_EMAIL, U5_DTCAD, U5_DTCADAS 
from AC8VIEW, OXICLOUD23.dbo.SU5010 with (nolock)
where AC8_CODCON = U5_CODCONT
AND OXICLOUD23.dbo.SU5010.D_E_L_E_T_ = ''

SELECT * FROM SU5VIEW1

ALTER VIEW SU5VIEW1 AS
select 
A1_COD,
A1_LOJA,
U5_CODCONT,
U5_CONTAT, -- NOME
U5_SOBRENO, -- SOBRENOME
ISNULL((select TOP 1 AGB_DDD from OXICLOUD23.dbo.AGB010 DDDFONE where DDDFONE.AGB_ENTIDA = 'SU5' and DDDFONE.AGB_CODENT = U5_CODCONT and DDDFONE.AGB_TIPO = '2' and DDDFONE.AGB_PADRAO = '1' and DDDFONE.D_E_L_E_T_ = ''), U5_DDD) AS U5_DDD_FONE, -- DDD FONE
ISNULL((select TOP 1 AGB_TELEFO from OXICLOUD23.dbo.AGB010 FONE where FONE.AGB_ENTIDA = 'SU5' and FONE.AGB_CODENT = U5_CODCONT and FONE.AGB_TIPO = '2' and FONE.AGB_PADRAO = '1' and FONE.D_E_L_E_T_ = ''), U5_FONE) AS U5_FONE, -- FONE
(select TOP 1 AGB_DDD from OXICLOUD23.dbo.AGB010 DDDCEL where DDDCEL.AGB_ENTIDA = 'SU5' and DDDCEL.AGB_CODENT = U5_CODCONT and DDDCEL.AGB_TIPO = '5' and DDDCEL.AGB_PADRAO = '1' and DDDCEL.D_E_L_E_T_ = '') AS U5_DDD_CEL, -- DDD CELULAR
(select TOP 1 AGB_TELEFO from OXICLOUD23.dbo.AGB010 CEL where CEL.AGB_ENTIDA = 'SU5' and CEL.AGB_CODENT = U5_CODCONT and CEL.AGB_TIPO = '5' and CEL.AGB_PADRAO = '1' and CEL.D_E_L_E_T_ = '') AS U5_CELULAR, -- CELULAR
U5_EMAIL, U5_DTCAD, U5_DTCADAS 
from OXICLOUD23.dbo.AC8010 with (nolock), OXICLOUD23.dbo.SU5010 with (nolock), OXICLOUD23.dbo.SA1010 with (nolock)
where AC8_CODCON = U5_CODCONT
AND  AC8_CODENT = A1_COD+A1_LOJA
AND OXICLOUD23.dbo.SU5010.D_E_L_E_T_ = ''

--================================================================================================================

-- VENDEDORES
ALTER VIEW SA3010 AS
select A3_COD AS COD_VEND_PROTHEUS,
A3_CODUSR AS COD_USUARIO_PROTHEUS,
A3_FILVEN,A3_NOME, A3_NREDUZ, A3_EMAIL, A3_GEREN, A3_COMIS,-- '02' AS A3_ALCITEM, '01' AS A3_ALCPED,
A3_MSBLQL
from OXICLOUD23.dbo.SA3010 with (nolock)
where OXICLOUD23.dbo.SA3010.D_E_L_E_T_ = ''


--================================================================================================================

--PRODUTOS (FILTRO: B1_DTCADAS)

SELECT COUNT(*) FROM SB1010 

ALTER VIEW SB1010 AS
select B1_IRRF,B1_GRUPO,B1_MARCA,B1_COD,B1_SUBGRUP,B1_DESC,
(select SUM(est_ar.B2_QATU) from OXICLOUD23.dbo.SB2010 est_ar where est_ar.B2_FILIAL = '01' AND est_ar.B2_COD = B1_COD and est_ar.D_E_L_E_T_ = '') AS ESTOQUE_AR,
(select SUM(est_sc.B2_QATU) from OXICLOUD23.dbo.SB2010 est_sc where est_sc.B2_FILIAL = '02' AND est_sc.B2_COD = B1_COD and est_sc.D_E_L_E_T_ = '') AS ESTOQUE_SC,
'AR: '+CONVERT(VARCHAR,(select SUM(est_ar.B2_QATU) from OXICLOUD23.dbo.SB2010 est_ar where est_ar.B2_FILIAL = '01' AND est_ar.B2_COD = B1_COD and est_ar.D_E_L_E_T_ = ''))+';'+
'SC: '+CONVERT(VARCHAR,(select SUM(est_sc.B2_QATU) from OXICLOUD23.dbo.SB2010 est_sc where est_sc.B2_FILIAL = '02' AND est_sc.B2_COD = B1_COD and est_sc.D_E_L_E_T_ = '')) AS B1_ESTOQUE,
ZZ8_PRLIST,ZZ8_PRMIN,ZZ8_DESC,
--(select ZOHO.dbo.GetPrvOfe(B1_COD,'028',1)) AS ZZ8_PRMINOFER, -- PREÇO DEFAULT 28 DIAS
--ROUND((select ZOHO.dbo.GetPrvOfe(B1_COD,'028',1))-((select ZOHO.dbo.GetPrvOfe(B1_COD,'028',1))*0.01),2) AS ALCADA1, -- PRECO VENDA -1%
--ROUND(ZZ8_PRLIST-(ZZ8_PRLIST*0.02),2) AS ALCADA2, -- PRECO VENDA -2%
--ROUND(ZZ8_PRLIST-(ZZ8_PRLIST*0.05),2) AS ALCADA5, -- PRECO VENDA -5%
--ROUND(ZZ8_PRLIST-(ZZ8_PRLIST*0.10),2) AS ALCADA10, -- PRECO VENDA -10%
--ROUND(ZZ8_PRLIST-(ZZ8_PRLIST*0.20),2) AS ALCADA20, -- PRECO VENDA -20%
--ROUND(ZZ8_PRLIST-(ZZ8_PRLIST*0.30),2) AS ALCADA30, -- PRECO VENDA -30%
--'0' AS ALCADA100, -- PRECO VENDA -100%
(select MAX(D2.D2_EMISSAO) from OXICLOUD23.dbo.SD2010 D2 where D2.D_E_L_E_T_ = '' and D2.D2_COD = B1_COD) AS DT_ULT_VEND,
CONVERT(VARCHAR(8000),CONVERT(VARBINARY(8000),B5_DESCSER)) AS ESPECIFICACAO,
B1_CODBAR AS COD_BAR_OXI,B1_CODBOXI AS COD_BAR_FORN_EAN, B1_QE AS LOTE, B1_OXQTMUL AS MULTIPLO,
B1_MSBLQL,B1_UM,B1_PICMENT,B1_EMIN,B1_EMAX,B1_PROC,B1_FABRIC,B1_IMPORT,B1_PESO,B1_PESBRU,B1_LOCAL1,
B1_LOCAL2,B1_LOCAL3,B1_LOCAL10,B1_DTCAD,B1_UCOM,'1' AS B1_GARANT,B1_POSIPI,B1_TIPO, B1_DTCADAS, '00:00' AS B1_HORAI,
B1_POSIPI AS B1_CLASFIS --  CLASSIFICACAO FISCAL (NCM)
, BM_DESC AS DESC_GRUPO
, ZZ3_DESC AS DESC_SUBGRUPO
, ZZ1_DESC AS DESC_MARCA
from OXICLOUD23.dbo.SB1010 with (nolock)
left join OXICLOUD23.dbo.ZZ8010 with (nolock) on ZZ8_PROD = B1_COD and OXICLOUD23.dbo.ZZ8010.D_E_L_E_T_ = ''
left join OXICLOUD23.dbo.SB5010 with (nolock) on B5_COD = B1_COD and OXICLOUD23.dbo.SB5010.D_E_L_E_T_ = ''
left join OXICLOUD23.dbo.SBM010 with (nolock) on BM_GRUPO = B1_GRUPO and OXICLOUD23.dbo.SBM010.D_E_L_E_T_ = ''
left join OXICLOUD23.dbo.ZZ3010 with (nolock) on ZZ3_COD = B1_SUBGRUP and OXICLOUD23.dbo.ZZ3010.D_E_L_E_T_ = ''
left join OXICLOUD23.dbo.ZZ1010 with (nolock) on ZZ1_MARCA = B1_MARCA and OXICLOUD23.dbo.ZZ1010.D_E_L_E_T_ = ''
WHERE OXICLOUD23.dbo.SB1010.D_E_L_E_T_ = ''
--and B1_COD = '030750072'

/*
update OFICIAL
set OFICIAL.B1_DTCAD = COPIA.B1_DTCAD,
    OFICIAL.B1_DTCADAS = COPIA.B1_DTCADAS,
	OFICIAL.B1_UCOM = COPIA.B1_UCOM
from OXICLOUD23.dbo.SB1010 OFICIAL,
     TESTES.dbo.SB1010 COPIA
where OFICIAL.B1_COD = COPIA.B1_COD
*/

select distinct UA_STATUS from SUA010

--================================================================================================================

--ORÇAMENTO
ALTER VIEW SUAVIEW AS
select UA_FILIAL,
       UA_NUM,
	   UA_CLIENTE,
	   UA_LOJA,
	   UA_NUMSC5,
	   UA_NUMSL1,
	   UA_CONDPG,
	   UA_VEND,
	   UA_CODCAMP,
	   UA_FORMPG,
	   UA_FRETE,
	   UA_VALBRUT,
	   UA_VLRLIQ,
	   UA_DESCONT,
	   UA_TPFRETE,
	   UA_ORIGORC,
	   UA_TRANSP,
	   UA_DOC,
	   UA_SERIE,
	   UA_EMISNF,
       UA_DTREVIS, 
	   UA_HRREVIS, 
	   UA_DTCANC, 
	   UA_MOTCANC, 
	   UA_DTLIM, 
	   UA_EMISSAO, 
	   UA_CODCONT,
       -- case UA_STATUS
         --  when 'NF.' THEN 'NF'
         --  when 'SUP' THEN 'NF'
         --  else UA_STATUS END  AS UA_STATUS, 
       CASE 
	       WHEN UA_NUMSC5 = '' AND UA_NUMSL1 = '' THEN 'AB'    -- AB = ORCAMENTO SEM PEDIDO                --** ADICIONADO FÁBIO E ADRIANO
		   ELSE 'PD'  END      AS UA_STATUS,                   -- PD = ORCAMENTO COM PEDIDO CONFIRMADO     --** ADICIONADO FÁBIO E ADRIANO
	   UA_CODLIG               AS COD_OCORRENCIA,               --** ADICIONADO FÁBIO E ADRIANO
	   UA_PROXLIG              AS DATA_RETORNO,                 --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_REGION           AS COD_REGIAO_CLIENTE,           --** ADICIONADO FÁBIO E ADRIANO   
	   CLI.A1_COD_MUN          AS COD_MUNIC_CLIENTE,            --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_EST              AS SIGLA_ESTADO_CLIENTE,         --** ADICIONADO FÁBIO E ADRIANO 
	   CLI.A1_CODPAIS          AS COD_PAIS_CLIENTE,             --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_CNAE             AS CNAE_PRINC_CLIENTE            --** ADICIONADO FÁBIO E ADRIANO
  from OXICLOUD23.dbo.SUA010 UA
  left join (select US_COD 
               from OXICLOUD23.dbo.SUS010 US 
			  where US_COD not in (select A1_COD 
			                         from OXICLOUD23.dbo.SA1010 A1 									      
									where A1.D_E_L_E_T_ = '') 
				and US.D_E_L_E_T_ = '')      AS TAB    on UA_CLIENTE = US_COD
  LEFT OUTER JOIN OXICLOUD23.dbo.SF2010      AS F2     ON F2_FILIAL  = UA_FILIAL     AND F2_DOC      = UA_DOC     AND F2_SERIE = UA_SERIE AND F2.D_E_L_E_T_<> '*'
  JOIN OXICLOUD23.dbo.SA1010                 AS CLI    ON CLI.A1_COD = UA.UA_CLIENTE AND CLI.A1_LOJA = UA.UA_LOJA  --** ADICIONADO FÁBIO E ADRIANO
 WHERE UA.D_E_L_E_T_<>'*' 
   AND UA_CLIENTE <> '004771'
   and UA_EMISSAO >= '20190101'
   and TAB.US_COD is null
--AND UA_ORIGORC <> '2'
--AND UA_NUMSL1 =''
--and UA_NUMSC5 = '497041'
--AND UA_EMISNF BETWEEN '20190101' AND '20190831'
--AND UA_EMISSAO BETWEEN '20200101' AND '20201231'
--and UA_DOC = '' and UA_STATUS <> 'CAN' -- ORCAMENTOS ABERTOS (CRM)




select *
  from OXICLOUD23.dbo.SUS010 US    --- TABELA DE PROSPECTS

  SELECT * FROM SUAVIEW ORDER BY UA_EMISSAO DESC -- WHERE UA_NUM IN ('855555' ,'138476')

  SELECT UA_NUMSL1,UA_NUMSC5,UA_STATUS, * FROM SUA010 WHERE   UA_NUM IN ('855555' ,'138476') AND UA_FILIAL = '01'

  UPDATE SUA010 SET UA_LIBFAT = 'N' WHERE   UA_NUM IN ('855555' ,'138476') AND UA_FILIAL = '01'
  UA_STATUS = 'SUP'

--ITENS ORÇAMENTO
ALTER VIEW SUBVIEW AS
select UB_FILIAL,UB_NUM,UB_ITEM,UB_PRODUTO,UB_QUANT,UB_VRUNIT,
CASE SUB.D_E_L_E_T_
WHEN '' THEN UB_VLRITEM
ELSE 0
END AS UB_VLRITEM,
UB_PRCTAB AS UB_PRCTAB_ORI, 0 AS UB_VALDESC, 0 AS IMPOSTOS,
CASE SUB.D_E_L_E_T_
WHEN '*' THEN '000014'
ELSE ''
END AS UB_MOTCANC
from OXICLOUD23.dbo.SUB010 SUB
inner join SUAVIEW SUA
on UA_NUM = UB_NUM and UA_FILIAL = UB_FILIAL
--Where UA_EMISNF BETWEEN '20190101' AND '20190831'
--where UA_EMISSAO BETWEEN '20190101' AND '20191211'
--and UA_DOC = '309693'

select F2_DOC, F2_SERIE, F2_FILIAL, (select distinct from SD2010 where D2_EMISSAO >= '20140101' and D_E_L_E_T_ = '' group by D2_DOC, D2_SERIE, D2_FILIAL having COUNT(D2_PEDIDO) > 1

select * from SC6010 where C6_NUM = '496013'

select * from SD2010 where D2_DOC = '309693'

--================================================================================================================

select B1_DTCADAS, B1_HORAI from OXICLOUD23.dbo.SB1010 SB1

select * from OXICLOUD23.dbo.SC5010 SC5 where C5_EMISSAO >= '20140101' and C5_HORAI <> ''

--PEDIDOS CRM
ALTER VIEW SC5010 AS
SELECT C5_FILIAL,  
       C5_NUM,
	   UA_NUM AS ORC, 
	   C5_EMISSAO,
	   C5_TIPO,
	   C5_CLIENTE,
	   C5_LOJAENT,
	   C5_LOJACLI,
	   C5_VEND1,
	   C5_CONDPAG,
	   C5_TRANSP,
       C5_PRIOR,
	   C5_COMIS1,
	   C5_TPFRETE,
	   C5_NOTA,
	   C5_SERIE,
	   C5_MENNOTA, 
	   ZRL_DATA, 
	   ZRL_HORA AS C5_HORAI,
       CASE SC5.D_E_L_E_T_
          WHEN '' THEN 'OK'
          ELSE 'CANCELADO'
          END AS C5_STATUS,
       CLI.A1_REGION           AS COD_REGIAO_CLIENTE,           --** ADICIONADO FÁBIO E ADRIANO   
	   CLI.A1_COD_MUN          AS COD_MUNIC_CLIENTE,            --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_EST              AS SIGLA_ESTADO_CLIENTE,         --** ADICIONADO FÁBIO E ADRIANO 
	   CLI.A1_CODPAIS          AS COD_PAIS_CLIENTE,             --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_CNAE             AS CNAE_PRINC_CLIENTE            --** ADICIONADO FÁBIO E ADRIANO
  FROM OXICLOUD23.dbo.SC5010 SC5
  left join OXICLOUD23.dbo.ZRL010   ZRL on ZRL_NUMPED = C5_NUM and ZRL_FILIAL = C5_FILIAL and ZRL.D_E_L_E_T_ = '' and ZRL_ACAO = 'GERACAO DO PEDIDO' and ZRL.R_E_C_N_O_ = (select MIN(ZRL2.R_E_C_N_O_) from OXICLOUD23.dbo.ZRL010 ZRL2 where ZRL.ZRL_NUMPED = ZRL2.ZRL_NUMPED and ZRL.ZRL_FILIAL = ZRL2.ZRL_FILIAL and ZRL2.ZRL_ACAO = 'GERACAO DO PEDIDO')
  left join OXICLOUD23.dbo.SUA010   UA  on UA_FILIAL  = C5_FILIAL and UA_NUMSC5 = C5_NUM
  JOIN OXICLOUD23.dbo.SA1010        CLI ON CLI.A1_COD = SC5.C5_CLIENTE AND CLI.A1_LOJA = SC5.C5_LOJACLI  --** ADICIONADO FÁBIO E ADRIANO
 where C5_EMISSAO >= '20190101'
   and C5_CLIENTE not in ('004771', '000268')
   and C5_TIPO not in ('D', 'B')
   and C5_NOTA <> ''
   and UA_NUM is not null
--and C5_EMISSAO between '20200101' AND '20200131' and SC5.D_E_L_E_T_ = ''


--ITENS PEDIDOS CRM
ALTER VIEW SC6010 AS
SELECT C6_FILIAL,C6_ITEM,C6_PRODUTO,C6_QTDVEN,C6_PRCVEN,C6_PRMIN,C6_VALOR,
C6_PRCVEN*C6_QTDVEN AS TOTAL_VEN,
CASE C6_PRODUTO
when '999999999' then C6_PRCVEN*C6_QTDVEN
else C6_PRMIN*C6_QTDVEN END AS TOTAL_MIN,
C6_LOCAL,C6_QTDENT,C6_QTDENT2,C6_CLI,C6_LOJA,C6_DATFAT,C6_NOTA,C6_SERIE,C6_NUM, 0 AS C6_VALDESC, 0 AS IMPOSTOS,
CASE SC6.D_E_L_E_T_
WHEN '' THEN 'OK'
ELSE 'CANCELADO'
END AS C6_STATUS
FROM OXICLOUD23.dbo.SC6010 SC6
inner join SC5010 SC5
on C5_NUM = C6_NUM and C5_FILIAL = C6_FILIAL
--where C5_EMISSAO between '20190101' AND '20191231'

--===============================================================================================================

--PEDIDOS LOJA
ALTER VIEW SL1010 AS
SELECT L1_FILIAL,
       L1_NUM,
	   UA_NUM AS ORC, 
	   L1_VEND,
	   L1_COMIS,
	   L1_CLIENTE,
	   L1_LOJA,
	   L1_TIPOCLI,--L1_VLRTOT,
       L1_VLRLIQ AS L1_VLRTOT,
       L1_DTLIM,
	   L1_NUMCFIS,
       L1_DOC,
	   L1_SERIE,
	   L1_EMISNF,
	   L1_CONDPG,
	   L1_FORMPG,
	   L1_EMISSAO,
       L1_DOCCANC,
	   L1_DATCANC,
       L1_HORA, 
	   L1_HORAI,
	   CLI.A1_REGION           AS COD_REGIAO_CLIENTE,           --** ADICIONADO FÁBIO E ADRIANO   
	   CLI.A1_COD_MUN          AS COD_MUNIC_CLIENTE,            --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_EST              AS SIGLA_ESTADO_CLIENTE,         --** ADICIONADO FÁBIO E ADRIANO 
	   CLI.A1_CODPAIS          AS COD_PAIS_CLIENTE,             --** ADICIONADO FÁBIO E ADRIANO
	   CLI.A1_CNAE             AS CNAE_PRINC_CLIENTE            --** ADICIONADO FÁBIO E ADRIANO
  FROM OXICLOUD23.dbo.SL1010            L1  with (nolock)
 INNER JOIN OXICLOUD23.dbo.SU7010       U7  with (nolock) ON U7_CODVEN  = L1_VEND        AND U7.D_E_L_E_T_<> '*'
 INNER JOIN OXICLOUD23.dbo.SA3010       A3  with (nolock) ON A3_COD     = L1_VEND        AND A3.D_E_L_E_T_<> '*'
  left join OXICLOUD23.dbo.SUA010       UA  with (nolock) on UA_FILIAL  = L1_FILIAL      and UA_NUMSL1 = L1_NUM
  LEFT OUTER JOIN OXICLOUD23.dbo.SF2010 F2  with (nolock) ON F2_FILIAL  = L1_FILIAL      AND F2_DOC = L1_DOC AND F2_SERIE = L1_SERIE AND F2.D_E_L_E_T_<> '*'
  JOIN OXICLOUD23.dbo.SA1010            CLI with (nolock) ON CLI.A1_COD = L1.L1_CLIENTE  AND CLI.A1_LOJA = L1.L1_LOJA  --** ADICIONADO FÁBIO E ADRIANO
where L1_EMISSAO >= '20190101'
AND L1.D_E_L_E_T_<>'*' AND L1_CLIENTE <> '004771'
--and L1_EMISSAO = '20191111'
--and L1_EMISSAO between '20200101' AND '20200131'
--and L1_DOC <> ''
-- L1_DOC= '' ORCAMENTOS ABERTOS (LOJA)



--ITENS PEDIDOS LOJA
ALTER VIEW SL2010 AS
SELECT L2_NUM,L2_PRODUTO,L2_ITEM,L2_DESCRI,L2_QUANT,L2_VRUNIT,L2_VLRITEM,
L2_LOCAL,L2_UM,L2_VALDESC,L2_TES,L2_CF,
L2_VENDIDO,L2_DOC,L2_SERIE,L2_PDV,L2_VALICM,L2_BASEICM,L2_EMISSAO,L2_DESCPRO,L2_PRCTAB,L2_GRADE,L2_FILIAL,L2_VEND,
L2_OXQTCON,L2_VALPS2,L2_VALCF2,L2_BASEPS2,L2_BASECF2,L2_ALIQPS2,L2_ALIQCF2,L2_SEGUM,
CASE SL2.D_E_L_E_T_
WHEN '' THEN 'OK'
ELSE 'CANCELADO'
END AS L2_STATUS
FROM OXICLOUD23.dbo.SL2010 SL2 with (nolock)
inner join SL1010 SL1
on L1_NUM = L2_NUM and L1_FILIAL = L2_FILIAL
--Where L1_EMISSAO between '20190101' AND '20201231'

--===============================================================================================================

/*
use ZOHO
set implicit_transactions off

-- CRIANDO CÓPIAS PARA LIBERAR TABELAS
DROP TABLE ZOHO.dbo.SF2BKPZ
DROP TABLE ZOHO.dbo.SD2BKPZ
DROP TABLE ZOHO.dbo.SL1BKPZ
DROP TABLE ZOHO.dbo.SC6BKPZ
DROP TABLE ZOHO.dbo.SUABKPZ
DROP TABLE ZOHO.dbo.SF3BKPZ
DROP TABLE ZOHO.dbo.SD1BKPZ
DROP TABLE ZOHO.dbo.SF1BKPZ

select * into SF2BKPZ from OXICLOUD23.dbo.SF2010 where F2_EMISSAO >= '20140101'
select D2.* into SD2BKPZ from OXICLOUD23.dbo.SD2010 D2 inner join SF2BKPZ on F2_FILIAL = D2_FILIAL and F2_SERIE = D2_SERIE and F2_DOC = D2_DOC
select * into SC6BKPZ from OXICLOUD23.dbo.SC6010 where D_E_L_E_T_ <> '*'
select * into SL1BKPZ from OXICLOUD23.dbo.SL1010 where L1_EMISSAO >= '20140101'
select * into SUABKPZ from OXICLOUD23.dbo.SUA010 where UA_EMISSAO >= '20140101'
select * into SF3BKPZ from OXICLOUD23.dbo.SF3010 where F3_DTCANC >= '20140101'
select * into SF1BKPZ from OXICLOUD23.dbo.SF1010 where F1_EMISSAO >= '20140101'
select D1.* into SD1BKPZ from OXICLOUD23.dbo.SD1010 D1 inner join SF1BKPZ on F1_FILIAL = D1_FILIAL and F1_SERIE = D1_SERIE and F1_DOC = D1_DOC
*/

--NF SAIDA (CRM) / CUPOM (LOJA)
ALTER VIEW SF2010 AS
-- LOJA
select distinct F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,SUM(D2_TOTAL+D2_VALIPI+D2_VALFRE) AS F2_VALBRUT,
SUM(D2_TOTAL+D2_VALIPI+D2_VALFRE) AS F2_VALMIN,
F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,
F2_FILATR,F2_CHVNFE,F2_PCOM1,
case F2_ESPECI1
WHEN 'SATCE' THEN 'CF'
ELSE 'NF' END AS F2_ESPECIE,
'' F3_DTCANC,
'' F3_OBSERV,
F2_HORA,
'FATURADA' AS TIPO, F2_TIPO,D2_DOC,L1_FILIAL,L1_EMISSAO,F2_COND
FROM OXICLOUD23.dbo.SD2010 D2 with (nolock)
INNER JOIN OXICLOUD23.dbo.SF2010 F2 with (nolock) ON F2_DOC = D2_DOC AND F2_SERIE = D2_SERIE AND F2_EMISSAO = F2_EMISSAO AND F2.D_E_L_E_T_<>'*' AND F2_FILIAL = D2_FILIAL  
INNER JOIN OXICLOUD23.dbo.SA3010 A3 with (nolock) ON A3_COD = F2_VEND1 AND A3.D_E_L_E_T_ <>'*'
INNER JOIN OXICLOUD23.dbo.SUM010 TT with (nolock) ON UM_CARGO = A3_CARGO AND TT.D_E_L_E_T_ <>'*'
INNER JOIN OXICLOUD23.dbo.SL1010 L1 with (nolock) ON F2_DOC = L1_DOC AND F2_SERIE = L1_SERIE AND F2_FILIAL = L1_FILIAL AND L1.D_E_L_E_T_<> '*'
WHERE F2_DUPL <>''
AND F2_TIPO NOT IN ('D','B','P') 
AND D2_TES NOT IN ('571') AND D2.D_E_L_E_T_ <> '*'
and F2_EMISSAO >= '20190101'
--and F2_EMISSAO between '20190101' AND '202500131'
--and F2_COND <> 'CN'
group by F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,F2_FILATR,F2_CHVNFE,F2_PCOM1,F2_ESPECI1, F2_HORA, F2_TIPO,
D2_DOC,L1_FILIAL,L1_EMISSAO, F2_COND

UNION ALL -- CRM
select distinct F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,SUM(D2_TOTAL+D2_VALIPI+D2_VALFRE) AS F2_VALBRUT,
--SUM(D2_TOTAL+D2_VALIPI+D2_VALFRE) AS F2_VALMIN,
SUM((C6_PRMIN*C6_QTDVEN)+D2_VALIPI+D2_VALFRE) AS F2_VALMIN,
F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,
F2_FILATR,F2_CHVNFE,F2_PCOM1,
case F2_ESPECI1
WHEN 'SATCE' THEN 'CF'
ELSE 'NF' END AS F2_ESPECIE,
'' F3_DTCANC,
'' F3_OBSERV,
F2_HORA,
'FATURADA' AS TIPO, F2_TIPO,D2_DOC,UA_FILIAL,UA_EMISSAO, F2_COND
FROM OXICLOUD23.dbo.SD2010 D2 with (nolock)
INNER JOIN OXICLOUD23.dbo.SF2010 F2 with (nolock) ON F2_DOC=D2_DOC AND F2_SERIE=D2_SERIE AND F2_EMISSAO=F2_EMISSAO AND F2.D_E_L_E_T_<>'*' AND F2_FILIAL=D2_FILIAL  
INNER JOIN OXICLOUD23.dbo.SA3010 A3 with (nolock) ON A3_COD=F2_VEND1 AND A3.D_E_L_E_T_<>'*'
INNER JOIN OXICLOUD23.dbo.SUM010 TT with (nolock) ON UM_CARGO=A3_CARGO AND TT.D_E_L_E_T_<>'*'
INNER JOIN OXICLOUD23.dbo.SC6010 C6 with (nolock) ON C6_NUM=D2_PEDIDO AND C6_ITEM=D2_ITEMPV AND C6_PEDCLI<>'' AND C6.D_E_L_E_T_<>'*' AND C6_CLI=D2_CLIENTE
LEFT OUTER JOIN OXICLOUD23.dbo.SUA010 UA with (nolock) ON F2_DOC=UA_DOC AND F2_SERIE=UA_SERIE AND F2_FILIAL=UA_FILIAL AND UA.D_E_L_E_T_<>'*'
AND UA_ORIGORC<>'2' AND UA_NUMSL1=''
WHERE F2_DUPL <>''
AND F2_TIPO NOT IN ('D','B','P') 
AND D2_TES NOT IN ('571') AND D2.D_E_L_E_T_ <> '*'
and F2_EMISSAO >= '20190101'
and UA_NUM = (select MAX(UA2.UA_NUM) from OXICLOUD23.dbo.SUA010 UA2 where UA2.UA_DOC = F2_DOC and UA2.UA_SERIE = F2_SERIE and UA2.UA_FILIAL = F2_FILIAL)
--and F2_EMISSAO between '20190101' AND '20250131'
--and F2_DOC = '309693' AND F2_FILIAL='01' AND F2_SERIE= '1'
group by F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,F2_FILATR,F2_CHVNFE,F2_PCOM1,F2_ESPECI1,F2_HORA,F2_TIPO,
D2_DOC,UA_FILIAL,UA_EMISSAO, F2_COND

UNION ALL -- DEVOLUCOES
SELECT distinct F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,SUM(D2_TOTAL+D2_VALFRE+D2_VALIPI) AS F1_VALBRUT, SUM(D2_TOTAL+D2_VALIPI+D2_VALFRE) AS F2_VALMIN, F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,
CASE F2_FILATR WHEN '' THEN '01' ELSE F2_FILATR END AS F2_FILATR,
F2_CHVNFE,F2_PCOM1,
case F2_ESPECI1
WHEN 'SATCE' THEN 'CF'
ELSE 'NF' END AS F2_ESPECIE,
'' F3_DTCANC,
'' F3_OBSERV,
F2_HORA,
'DEVOLUCAO' AS TIPO,F2_TIPO,F2_DOC,D2_FILIAL,D2_EMISSAO, F2_COND
FROM OXICLOUD23.dbo.SD2010 D2 with (nolock)
INNER JOIN OXICLOUD23.dbo.SF2010 F2 ON D2_FILIAL = F2_FILIAL AND D2_DOC = F2_DOC AND D2_SERIE = F2_SERIE-- AND D2_CLIENTE = F2_CLIENTE
AND D2_LOJA = F2_LOJA AND F2_TIPO = 'D' AND F2.D_E_L_E_T_ <> '*'
AND F2_EMISSAO BETWEEN '20190101' AND '20250131'
INNER JOIN OXICLOUD23.dbo.SF4010 F4 with (nolock) ON D2_TES = F4_CODIGO AND F4_DUPLIC = 'S' AND F4.D_E_L_E_T_ <> '*'
WHERE D2.D_E_L_E_T_ <> '*' 
GROUP BY F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA,F2_EMISSAO,F2_EST,F2_TIPOCLI,F2_VALBRUT,F2_TRANSP,F2_VEND1,F2_FILIAL,F2_PREFIXO,F2_CHVNFE,F2_PCOM1,F2_ESPECI1,F2_FILATR,F2_HORA,F2_TIPO,
F2_DOC,D2_FILIAL,D2_EMISSAO, F2_COND

UNION ALL -- CANCELADAS
select DISTINCT F3_NFISCAL,F3_SERIE,F3_CLIEFOR,F3_LOJA,F3_EMISSAO,F3_ESTADO,'' F2_TIPOCLI, 0 F2_VALBRUT, 0 F2_VALMIN, '' F2_TRANSP,'' F2_VEND1,F3_FILIAL,'' F2_PREFIXO,'' F2_FILATR,''F2_CHVNFE,''F2_PCOM1
,case WHEN F3_OBSERV LIKE 'CF-e-SAT%' THEN 'CF' ELSE 'NF' END AS F2_ESPECIE
,ISNULL(F3_DTCANC,'') F3_DTCANC
,ISNULL(F3_OBSERV,'') F3_OBSERV
,'' F2_HORA,
'CANCELADA' AS TIPO,'' F2_TIPO, '' D2_DOC,'' UA_FILIAL,'' UA_EMISSAO, '' F2_COND
from OXICLOUD23.dbo.SF3010 F3 with (nolock)
where F3.D_E_L_E_T_ = '' and F3_DTCANC >= '20119101'
and F3_FILIAL in ('01', '02')
and F3_CFO > '4999'
and F3_EMISSAO between '20190101' AND '20220131'

select COUNT(1) from SF2COPY
select COUNT(1) from SF2LITE

/*
select * into SF2BKPZ where F2_EMISSAO between '20190101' AND '20191231'
select D2.* into SD2BKPZ from OXICLOUD23.dbo.SD2010 D2 inner join OXICLOUD23.dbo.SF2010 on F2_FILIAL = D2_FILIAL and F2_SERIE = D2_SERIE and F2_DOC = D2_DOC and F2_EMISSAO between '20190101' AND '20191231'
select D1.* into SD1BKPZ from OXICLOUD23.dbo.SD1010 D1 inner join OXICLOUD23.dbo.SF1010 on F1_FILIAL = D1_FILIAL and F1_SERIE = D1_SERIE and F1_DOC = D1_DOC and F1_EMISSAO between '20190101' AND '20191231'

select * from SD2BKPZ
select * from SD1BKPZ

DROP TABLE ZOHO.dbo.SD2BKPZ
DROP TABLE ZOHO.dbo.SD1BKPZ
*/

--ITENS CUPOM / NF SAÍDA
ALTER VIEW SD2010 AS
-- NF SAIDA
select D2_FILIAL,D2_CLIENTE,D2_LOJA,D2_ITEM,D2_COD,D2_QUANT,D2_PRUNIT,D2_PRCVEN,D2_TOTAL,D2_CF,D2_PEDIDO,D2.D2_DOC,D2_LOCAL,D2_SERIE,D2_EMISSAO,D2_EST,D2_TIPO,D2_QTDEDEV,D2_CLASFIS,D2_ESPECIE
from OXICLOUD23.dbo.SD2010 D2 with (nolock)
inner join OXICLOUD23.dbo.SF2010 F2 with (nolock)
on F2_DOC = D2.D2_DOC
and F2_SERIE = D2_SERIE
and F2_FILIAL = D2_FILIAL
and F2_EMISSAO >= '20140101'-- and F2.TIPO <> 'CANCELADA'
and F2_EMISSAO between '20200101' AND '20200131'
--and D2_DOC = '309693'

UNION ALL -- DEVOLDIDAS
select D1_FILIAL,'' D1_CLIENTE,D1_LOJA,D1_ITEM,D1_COD,D1_QUANT,D1_VUNIT,D1_VUNIT AS D1_PRCVEN,D1_TOTAL,D1_CF,D1_PEDIDO,D1_DOC,D1_LOCAL,D1_SERIE,D1_EMISSAO,'' D1_EST,D1_TIPO,D1_QTDEDEV,D1_CLASFIS,'' D1_ESPECIE
from OXICLOUD23.dbo.SD1010 D1
INNER JOIN OXICLOUD23.dbo.SF1010 F1 ON D1_FILIAL = F1_FILIAL AND D1_DOC = F1_DOC AND D1_SERIE = F1_SERIE AND D1_FORNECE = F1_FORNECE
AND D1_LOJA = F1_LOJA AND F1_TIPO = 'D' AND F1.D_E_L_E_T_ <> '*'
--AND F1_DTDIGIT BETWEEN '20190101' AND '20191231'
INNER JOIN OXICLOUD23.dbo.SF4010 F4 ON D1_TES = F4_CODIGO AND F4_DUPLIC = 'S' AND F4.D_E_L_E_T_ <> '*'
WHERE D1.D_E_L_E_T_ <> '*'

--===============================================================================================================

--NF ENTRADA
ALTER VIEW SF1010 AS
select F1_FILIAL,F1_DOC,F1_SERIE,F1_FORNECE,F1_LOJA,F1_COND,F1_DUPL,F1_EMISSAO,F1_EST,F1_FRETE,F1_BASEICM,F1_VALICM,F1_BASEIPI,F1_VALIPI,F1_VALMERC,F1_VALBRUT,F1_TIPO,F1_DTDIGIT,F1_DTLANC,F1_NFORIG,F1_SERORIG,F1_BASIMP6,F1_VALIMP6,F1_ESPECIE,F1_IMPORT,F1_BASEIR,F1_PREFIXO,F1_PEDVEND,F1_TIPODOC,F1_STATUS,F1_RECBMTO,F1_APROV, F1_HORA
from OXICLOUD23.dbo.SF1010
where F1_EMISSAO >= '20140101' AND D_E_L_E_T_ = ''
and F1_EMISSAO between '20200101' AND '20200131'

-- ITENS NF ENTRADA
ALTER VIEW SD1010 AS
select D1_FILIAL,D1_ITEM,D1_COD,D1_DESCR,D1_XITEMNF,D1_UM,D1_QUANT,D1_VUNIT,D1_TOTAL,D1_TES,D1_CF,D1_VALIPI,D1_VALICM,D1_IPI,D1_PICM,D1_SEGUM,D1_QTSEGUM,D1_LOCAL,D1_FORNECE,D1_LOJA,D1_CONTA,D1_DOC,D1_EMISSAO,D1_DTDIGIT,D1_SERIE,D1_PEDIDO,D1_ITEMPC,D1_NFORI,D1_SERIORI,D1_GRUPO,D1_TIPO,D1_ITEMORI,D1_TP,D1_QTDEDEV,D1_VALDEV,D1_ICMSRET,D1_SKIPLOT,D1_BRICMS,D1_DATORI,D1_BASEICM,D1_BASEIPI,D1_CLASFIS,D1_CUSTO,D1_BASIMP5,D1_BASIMP6,D1_VALIMP5,D1_VALIMP6,D1_ALQIMP5,D1_ALQIMP6,D1_QTDPEDI,D1_VALFRE,D1_RATEIO,D1_QTCONFE,D1_ICMNDES,D1_MARGEM,D1_ALIQSOL,D1_DFABRIC,D1_VALCSL,D1_ALQPIS,D1_ALQCOF,D1_ESPICM,D1_ESPCST,D1_GRPCST,D1_VLSLXML
from OXICLOUD23.dbo.SD1010 SD1
inner join OXICLOUD23.dbo.SF1010 SF1
on D1_DOC = F1_DOC and D1_SERIE = F1_SERIE and D1_FILIAL = F1_FILIAL and F1_EMISSAO >= '20140101' and SF1.D_E_L_E_T_ = '' and F1_EMISSAO between '20200101' AND '20200131'
where SD1.D_E_L_E_T_ = ''

--===============================================================================================================

--FORNECEDORES
ALTER VIEW SA2010 AS
select A2.A2_COD, A2.A2_LOJA, A2.A2_NOME, A2.A2_MUN, A2.A2_EST, A2.A2_PAIS, A2.A2_CGC,A2.A2_INSCR,A2.A2_TEL, A2.A2_NATUREZ, A2.A2_PRICOM, A2.A2_ULTCOM, A2.A2_NROCOM
from OXICLOUD23.dbo.SA2010 A2
where D_E_L_E_T_ = ''

--===============================================================================================================

-- TRANSPORTADORAS
ALTER VIEW SA4010 AS
select A4_COD, A4_NOME, A4_VIA, A4_COD_MUN, A4_MUN, A4_EST, A4_CODPAIS
from OXICLOUD23.dbo.SA4010
where D_E_L_E_T_ = '';

--===============================================================================================================

-- CONDICAO DE PAGAMENTO
ALTER VIEW SE4010 AS
select *
from OXICLOUD23.dbo.SE4010
where D_E_L_E_T_ = '';

--=======================================================================
CREATE VIEW  REGION  AS 
SELECT * 
FROM OXICLOUD23.dbo.SX5010 WHERE X5_TABELA = 'A2'
AND D_E_L_E_T_ = ''